name: mega-linter

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  mega-linter:
    name: mega-linter
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Commit"
        uses: actions/checkout@v2
      - name: Set SHA to be that of the present commit
        run: |
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            echo "GITHUB_SHA=$(cat $GITHUB_EVENT_PATH | jq -r .pull_request.head.sha)" >> $GITHUB_ENV
          fi
      - name: Test SHA value
        run: echo $GITHUB_SHA_SHORT
      - name: "Lint All files, Including Helmfiles"
        uses: cloudposse/actions/github/mega-linter@df45ed6
        env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
            PLUGINS: "https://raw.githubusercontent.com/cloudposse/actions/helmfile-mega-linter/github/mega-linter/mega-linter-plugin-helmfile/helmfile.megalinter-descriptor.yml"
